/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TELAS;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */

public class TelaCancelar extends javax.swing.JFrame {

    /**
     * Creates new form TelaCancelar
     */
    public TelaCancelar() {
        initComponents();
    }
    private TelaLista telaLista; // referência da tela principal

    public TelaCancelar(TelaLista telaLista) {
        initComponents();
        this.telaLista = telaLista;
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        // Garantir tamanho antes de escalar
        setSize(500, 550); // ou setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);//Centralizar na tela
        setLayout(null); // necessário para posicionamento manual
        setResizable(false);

        jtfIdPedidoCancel.setOpaque(false);
        jtfIdPedidoCancel.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        jtfIdPedidoCancel.setForeground(java.awt.Color.BLACK);
        jtfIdPedidoCancel.setBackground(new Color(0, 0, 0, 0)); // Totalmente transparente
        jtfIdPedidoCancel.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 22));

        jbtConfirmarCancelamento.setContentAreaFilled(true); // tira o fundo branco
        jbtConfirmarCancelamento.setBorderPainted(false);     // tira a borda
        jbtConfirmarCancelamento.setOpaque(false);            // permite transparência
        jbtConfirmarCancelamento.setFont(new Font("SansSerif", Font.BOLD, 20)); // ou outro tamanho
        jbtConfirmarCancelamento.setForeground(java.awt.Color.WHITE); // cor branca ou como a cor do fundo
        jbtConfirmarCancelamento.setBackground(new Color(20, 40, 60)); // Azul escuro (RGB)

        ImageIcon imagemOriginal = DAO.ImagemTelas.getImagem("telacancelar");

        if (imagemOriginal != null) {
            // Escala a imagem de acordo com a tela
            Image imagem = imagemOriginal.getImage().getScaledInstance(getWidth(), getHeight(), Image.SCALE_SMOOTH);
            JLabel fundo = new JLabel(new ImageIcon(imagem));
            fundo.setBounds(0, 0, getWidth(), getHeight());

            // Adiciona a imagem atrás dos componentes
            getContentPane().add(fundo);
            getContentPane().setComponentZOrder(fundo, getContentPane().getComponentCount() - 1);
        } else {
            System.out.println("Imagem de fundo não encontrada.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfIdPedidoCancel = new javax.swing.JTextField();
        jbtConfirmarCancelamento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtfIdPedidoCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfIdPedidoCancelActionPerformed(evt);
            }
        });

        jbtConfirmarCancelamento.setText("Confirmar Cancelamento");
        jbtConfirmarCancelamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtConfirmarCancelamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addComponent(jtfIdPedidoCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jbtConfirmarCancelamento, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(261, Short.MAX_VALUE)
                .addComponent(jtfIdPedidoCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jbtConfirmarCancelamento, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfIdPedidoCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfIdPedidoCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfIdPedidoCancelActionPerformed

    private void jbtConfirmarCancelamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtConfirmarCancelamentoActionPerformed
        try {
            int idCancelar = Integer.parseInt(jtfIdPedidoCancel.getText());

            try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_autopaint", "root", "")) {

                //  Verifica o status atual do pedido
                String sqlVerifica = "SELECT status_servico FROM servicos WHERE id_servico = ?";
                PreparedStatement stmtVerifica = conn.prepareStatement(sqlVerifica);
                stmtVerifica.setInt(1, idCancelar);
                ResultSet resultado = stmtVerifica.executeQuery();

                if (resultado.next()) {
                    String statusAtual = resultado.getString("status_servico");

                    if ("Cancelado".equalsIgnoreCase(statusAtual)) {
                        new TelaErroAdd("Este pedido já está cancelado.<br>Status atual: Cancelado").setVisible(true);
                        return;
                    }

                    if ("Finalizado".equalsIgnoreCase(statusAtual)) {
                        new TelaErroAdd("Este pedido já foi finalizado.<br>Status atual: Finalizado").setVisible(true);
                        return;
                    }

                    if ("Pendente".equalsIgnoreCase(statusAtual)) {
                        //  Executa o cancelamento
                        String sqlAtualiza = "UPDATE servicos SET status_servico = 'Cancelado' WHERE id_servico = ?";
                        PreparedStatement stmtAtualiza = conn.prepareStatement(sqlAtualiza);
                        stmtAtualiza.setInt(1, idCancelar);

                        int linhasAfetadas = stmtAtualiza.executeUpdate();

                        if (linhasAfetadas > 0) {
                            new TelaAddSucesso("Pedido cancelado com sucesso.<br>Status atualizado: Cancelado").setVisible(true);
                            telaLista.carregarPedidos();
                            this.dispose();
                        } else {
                            new TelaErroAdd("Erro ao cancelar pedido. Nenhum registro foi alterado.").setVisible(true);
                        }
                    } else {
                        new TelaErroAdd("Status do pedido não reconhecido: " + statusAtual).setVisible(true);
                    }

                } else {
                    new TelaErroAdd("ID não encontrado. Nenhum pedido corresponde.").setVisible(true);
                }

            }

        } catch (NumberFormatException e) {
            new TelaErroAdd("Digite um número válido para o ID.").setVisible(true);
        } catch (SQLException e) {
            new TelaErroAdd("Erro ao cancelar pedido: " + e.getMessage()).setVisible(true);
        }
    
    }//GEN-LAST:event_jbtConfirmarCancelamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(TelaCancelar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(TelaCancelar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(TelaCancelar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(TelaCancelar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new TelaCancelar().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtConfirmarCancelamento;
    private javax.swing.JTextField jtfIdPedidoCancel;
    // End of variables declaration//GEN-END:variables
}
